DROP PROCEDURE GARVIZU.SP_ADDESTUDIANTE;

CREATE OR REPLACE PROCEDURE GARVIZU."SP_ADDESTUDIANTE"
(
    CI VARCHAR2,
    NOMBRES VARCHAR2,
    APELLIDOS VARCHAR2,
    FECHANACIMIENTO DATE
)
AS 
BEGIN
    insert into estudiante (CI, NOMBRES, APELLIDOS, FECHA_NACIMIENTO)
                values (CI, NOMBRES, APELLIDOS, FECHANACIMIENTO);
    DBMS_OUTPUT.put_line(1);
    return;
END;
/