DROP PROCEDURE GARVIZU.SP_GETMATERIASCOMBO;

CREATE OR REPLACE PROCEDURE GARVIZU."SP_GETMATERIASCOMBO"
(        
    PERCURSORMATERIACOMBO OUT SYS_REFCURSOR
)
AS
BEGIN
    open PERCURSORMATERIACOMBO for    
  SELECT ID_MATERIA, NOMBRE
  FROM MATERIA;      
   
 End;
/