DROP PROCEDURE GARVIZU.SP_GETMATERIASALL;

CREATE OR REPLACE PROCEDURE GARVIZU."SP_GETMATERIASALL"
(        
    PERCURSORMATERIAALL OUT SYS_REFCURSOR
)
AS
BEGIN
    open PERCURSORMATERIAALL for    
  SELECT ID_MATERIA, SIGLA, NOMBRE
  FROM MATERIA;      
   
 End;
/