DROP PROCEDURE GARVIZU.SP_UPDATEINSCRIPCION;

CREATE OR REPLACE PROCEDURE GARVIZU."SP_UPDATEINSCRIPCION"
(
    I_ID number,
    I_MAT NUMBER,
    I_EST NUMBER,
    I_DESCRIPCION VARCHAR2    
)
AS 
BEGIN
    update inscripcion
    SET descripcion=I_DESCRIPCION     
    WHERE
    ID_INSCRIPCION=I_ID; 
    RETURN;   
END;
/